apiVersion: v1
kind: ConfigMap
metadata:
  name: pokesync-config
data:
  DB_HOST: database
  DB_PORT: "5432"
  DB_NAME: pokesync
  DB_USER: pokesync
  JWT_EXPIRATION_SECONDS: "3600"
  SPRING_PROFILES_ACTIVE: default
