apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: pokesync-frontend
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokesync-frontend
  template:
    metadata:
      labels:
        app: pokesync-frontend
    spec:
      containers:
        - name: frontend
          image: pokesync-frontend:deployment
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              memory: 128Mi
